### ISSUE TITLE
Update include in README example

### ISSUE THREAD

**Issue by jkosh44** [lemire/fast_float#10]
I'm pretty sure the include from the example in your README is incorrect. It has `#include "fast_float/parse_number.h"`, when it should be `#include "fast_float/fast_float.h"`. In your benchmarking code you have the second include
https://github.com/lemire/simple_fastfloat_benchmark/blob/a91ca26fa8b991593eb1c601d3232b6dfed72ff8/benchmarks/benchmark.cpp#L4
and also `fast_float.h` is not included by any other file and is where the `from_chars` is declared.
Patch for this fix is below. Thanks so much for the library, it's really useful!

```
diff --git a/README.md b/README.md
index 13239a5..24c307b 100644
--- a/README.md
+++ b/README.md
@@ -44,7 +44,7 @@ It will parse infinity and nan values.
 Example:
 
 ``` C++
-#include "fast_float/parse_number.h"
+#include "fast_float/fast_float.h"
 #include <iostream>
  
 int main() {
```

**Comment by lemire** [comment]
Will fix soon.

**Comment by lemire** [comment]
Fixing via https://github.com/lemire/fast_float/pull/11

**Comment by lemire** [comment]
Fixed. Thanks for the report.
