### ISSUE TITLE
Error in readme.

### ISSUE THREAD

**Issue by alexey-milovidov** [lemire/fast_float#21]
```
# parsing random integers in the range [0,1)
volume = 2.09808 MB 
netlib                                  :   294.33 MB/s (+/- 2.4 %)    14.03 Mint/s  
```

The word `integers` is a mistake, should be replaced to `floats`.
The name of `Mints/s` metric is also bogus.

**Comment by lemire** [comment]
You are correct. Thank you for the comment. I fixed it via a commit.
