### ISSUE TITLE
Performance tests on various distributions.

### ISSUE THREAD

**Issue by alexey-milovidov** [lemire/fast_float#22]
Uniformly distributed floats in [0, 1) don't represent typical datasets.

We can look at some other distributions (example from ClickHouse performance tests):
https://github.com/ClickHouse/ClickHouse/blob/master/tests/performance/float_parsing.xml

Clarifications about this perf test:
rand() is uniformly distributed UInt32;
rand64() is uniformly distributed UInt64;
In rand(1) and rand(2) the arguments are just tags to distinguish function calls, they behave in the same way as rand().

**Comment by lemire** [comment]
Thank you. 

This repository (fast_float) does not include benchmarks.

I will move your issue to https://github.com/lemire/simple_fastfloat_benchmark

**Comment by lemire** [comment]
Closing. Please go to https://github.com/lemire/simple_fastfloat_benchmark/issues/2
