### ISSUE TITLE
Big Endian support

### ISSUE THREAD

**Issue by kiszk** [lemire/fast_float#37]
I realized that the function `from_chars` with the exponential notion (e.g. `1e30`) with float always returns `0`.

This is because [this line](https://github.com/lemire/fast_float/blob/main/include/fast_float/parse_number.h#L110) always copies the first four bytes of uint64_t when we handle float. However, on big-endian platform, the value is stored in the last four bytes of `word` when we handle float.

This issue comes from https://github.com/apache/arrow/pull/8674

**Comment by lemire** [comment]
@kiszk Thanks for the report. We will gladly take a pull request. This being said, I do not have access to a big-endian system and I do not know how to do continuous integration tests for big-endian systems. Without proper testing in place, we cannot support big endian platforms reasonably. I believe travis added POWER support recently, but again, only little endian.

**Comment by lemire** [comment]
@kiszk  To be clear, you report one issue, but there might be other issues related to big-endian system. To be able to say that things work under big endian systems, we'd want to run our tests. I'll gladly take the patch you contributed to Arrow and make no fuss about it, but how do you know that it fixes all issues related to endianness?

**Comment by kiszk** [comment]
@lemire Thank you for your comment.

Regarding testing on BE, Travis CI s390x (BE) is available as written in https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z in addition to ppc64le.

**Comment by kiszk** [comment]
In addition, if you need System z Linux environment, you may want to see https://developer.ibm.com/components/ibm-linuxone/gettingstarted/ to get a free instance for (probably) 90 days.

**Comment by lemire** [comment]
I will see if I can run tests under x390x.

> to get a free instance for (probably) 90 days.

We really do want continuous integration support. It is not practical to claim to support a platform while only testing it sporadically using temporary access.

**Comment by lemire** [comment]
@kiszk  Thankfully, your pointers proved useful. It works.

I'll merge a fix soon.

**Comment by lemire** [comment]
Ok. I am preparing a release. It takes some time because I need to run exhaustive tests.

**Comment by kiszk** [comment]
Thank you for taking care of both endians.
