### ISSUE TITLE
MinGW32 build failure

### ISSUE THREAD

**Issue by pitrou** [lemire/fast_float#4]
When trying to integrate this library in Apache Arrow, we found it failed on our MinGW32 CI builds:
```
D:/a/arrow/arrow/cpp/src/arrow/vendored/fast_float/float_common.h: In function 'arrow_vendored::fast_float::value128 arrow_vendored::fast_float::full_multiplication(uint64_t, uint64_t)':
D:/a/arrow/arrow/cpp/src/arrow/vendored/fast_float/float_common.h:115:3: error: '__uint128_t' was not declared in this scope; did you mean 'uint32_t'?
  115 |   __uint128_t r = ((__uint128_t)value1) * value2;
      |   ^~~~~~~~~~~
      |   uint32_t
```

The following changes fixed it:
https://gist.github.com/pitrou/a77ab72cfda0b81bc95e9c81489ccd37
(from this changeset: https://github.com/apache/arrow/pull/8494/commits/077869d66dc5ccd05ba4dff427ff1161c972d6d9)

**Comment by pitrou** [comment]
Note that `_MSC_VER` only selects MSVC but `_WIN32` selects all Windows builds (including MinGW).

**Comment by lemire** [comment]
Fixed with https://github.com/lemire/fast_float/pull/5 

Tests added.
